 //const defaultEmployees = [

            const defaultEmployees = [
            {name:"Teboho-1 ", idCard: ""},
            {name: "Sipho G-2 ", idCard: ""},
            {name: "Johannes -3 ", idCard: ""},
            {name: "Mabuti -4 ", idCard: ""},
            {name: "Daniel -5 ", idCard: ""},
            {name: "ltumeleng -6 ", idCard: ""},
            {name: "Nelson M -7 ", idCard: ""},
            {name: "Saphulele -8 ", idCard: ""},
            {name: "Stephen -9 ", idCard: ""},
            {name: "Thabang -10 ", idCard: ""},
            {name: "Moeketsi -11 ", idCard: ""},
            {name: "Mpho-12 ", idCard: ""},
            {name: "Azisiwe -13 ", idCard: ""},
            {name: "Nonhqubela -14 ", idCard: ""},
            {name: "Sipho -15 ", idCard: ""},
            {name: "Tefo -16 ", idCard: ""},
            {name: "Thapelo -17 ", idCard: ""},
            {name: "Snell-18 ", idCard: ""},
            {name: "Puno -19 ", idCard: ""},
            {name: "Samuel-20 ", idCard: ""},
            {name: "Mahlomola -21 ", idCard: ""},
            {name: "Mojalefa-22 ", idCard: ""},
            {name: "Lindeiani -23 ", idCard: ""},
            {name: "Tumelo -24 ", idCard: ""},
            {name: "Meilucky-25 ", idCard: ""},
            {name: "Amohelang -26 ", idCard: ""},
            {name: "Kumalo MS -27 ", idCard: ""},
            {name: "Asonele -28 ", idCard: ""},
            {name: "Kabelo P-29 ", idCard: ""},
            {name: "Vuyisa -30 ", idCard: ""},
            {name: "William -31 ", idCard: ""},
            {name: "Nelson -32 ", idCard: ""},
            {name: "Thabo -33 ", idCard: ""},
            {name: "Isaac -34 ", idCard: ""},
            {name: "Hlongwane -35 ", idCard: ""},
            {name: "Nomswazi -36 ", idCard: ""},
            {name: "Kabelo-37 ", idCard: ""},
            {name: "Seipati-38 ", idCard: ""},
            {name: "James L-39 ", idCard: ""},
            {name: "Yandisa-40 ", idCard: ""},
            {name: "Sibongile -41 ", idCard: ""},
            {name: "Karabo -42 ", idCard: ""},
            {name: "Kamohelo -43 ", idCard: ""},
            {name: "Zwelinzema -44 ", idCard: ""},
            {name: "Selekane -45 ", idCard: ""},
            {name: "jackson -46 ", idCard: ""},
            {name: "Thabang M-47 ", idCard: ""},
            {name: "William D-48 ", idCard: ""},
            {name: "Makonyane -49 ", idCard: ""},
            {name: "Keketso -50 ", idCard: ""},
            {name: "Lerato P -51 ", idCard: ""},
            {name: "Winnie -52 ", idCard: ""},
            {name: "Karabo -53 ", idCard: ""},
            {name: "男Promise -C1 ", idCard: ""},
            {name: "Charles -C2 ", idCard: ""},
            {name: "Paress -C3 ", idCard: ""},
            {name: "Bashiru -C4 ", idCard: ""},
            {name: "Mariam-C5 ", idCard: ""},
            {name: "Rejoice -C6 ", idCard: ""},
            {name: "Fortunate -C7 ", idCard: ""},
            {name: "Ahmd -C8 ", idCard: ""},
            {name: "Joel-C9 ", idCard: ""},
            {name: "Cassim -C10 ", idCard: ""},
            {name: "Jafali-C11 ", idCard: ""},
            {name: "Polite -C12 ", idCard: ""},
            {name: "Ruth -C13 ", idCard: ""},
            {name: "女Moses -A1 ", idCard: ""},
            {name: "Luwes -A2 ", idCard: ""},
            {name: "Lucas -A3 ", idCard: ""},
            {name: "Affan-A4 ", idCard: ""},
            {name: "Toby-A5 ", idCard: ""},
            {name: "Jayden-A6 ", idCard: ""},
            {name: "Howard -A7 ", idCard: ""},
            {name: "Gift B-A8 ", idCard: ""},
            {name: "Ali-A9 ", idCard: ""},
            {name: "Lucky -A10 ", idCard: ""},
            {name: "Moses T-A11 ", idCard: ""},
            {name: "Samals -A12 ", idCard: ""},
            {name: "Alick -A13 ", idCard: ""},
            {name: "Joyce-A14 ", idCard: ""},
            {name: "Charles -A15 ", idCard: ""},
            {name: "Loveness -A16 ", idCard: ""},
            {name: "Cosmos -A17 ", idCard: ""},
            {name: "Mavvta -A18 ", idCard: ""},
            {name: "Kondwani -A19 ", idCard: ""},
            {name: "Mercy -A20 ", idCard: ""},
            {name: "Judith M -A21 ", idCard: ""},
            {name: "Lourence -A22 ", idCard: ""},
            {name: "inasio -A23 ", idCard: ""},
            {name: "Isaack -A24 ", idCard: ""},
            {name: "Frank -A25 ", idCard: ""},
            {name: "Jefrey -A26 ", idCard: ""},
            {name: "Eno-A27 ", idCard: ""},
            {name: "Terrence -A28 ", idCard: ""},
            {name: "Raffic -A29 ", idCard: ""},
            {name: "Cams -A30 ", idCard: ""},
            {name: "Mike -A31 ", idCard: ""},
            {name: "Saidi-A32 ", idCard: ""},
            {name: "David -A33 ", idCard: ""},
            {name: "Lenard -A34 ", idCard: ""},
            {name: "Aidu -A35 ", idCard: ""},
            {name: "Peter-A36 ", idCard: ""},
            {name: "Johan -A37 ", idCard: ""},
            {name: "Promise -A38 ", idCard: ""},
            {name: "Martha -A39 ", idCard: ""},
            {name: "Thomas -A40 ", idCard: ""},
            {name: "Ismail -A41 ", idCard: ""},
            {name: "Jabai Sai -A42 ", idCard: ""},
            {name: "Leo -A43 ", idCard: ""},
            {name: "Tadiwanosch -A44 ", idCard: ""},
            {name: "Mphatso -A45 ", idCard: ""},
            {name: "Adumu -A46 ", idCard: ""},
            {name: "Inok -A47 ", idCard: ""},
            {name: "Mathews -A48 ", idCard: ""},
            {name: "John Gomo -A49 ", idCard: ""},
            {name: "Duwo -A50 ", idCard: ""},
            {name: "Grant -A51 ", idCard: ""},
            {name: "Akim -A52 ", idCard: ""},
            {name: "Blyso -A53 ", idCard: ""},
            {name: "Chriss -A54 ", idCard: ""},
            {name: "James -A55 ", idCard: ""},
            {name: "重名C1-A38", idCard: ""}];
	
	
	